name: Daily Commit for 23f3000709@ds.study.iitm.ac.in

on:
  push:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at specified time
  workflow_dispatch:

permissions:
  contents: write  # Ensure GitHub Actions can push changes

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git for 23f3000709@ds.study.iitm.ac.in
        run: |
          git config --global user.name "23f3000709@ds.study.iitm.ac.in"
          git config --global user.email "23f3000709@ds.study.iitm.ac.in"

      - name: Make a Change for 23f3000709@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date) by 23f3000709@ds.study.iitm.ac.in" > last_run.txt  # Include email in the file

      - name: Commit and Push Changes for 23f3000709@ds.study.iitm.ac.in
        run: |
          git add last_run.txt
          git commit -m "Automated daily commit at $(date) by 23f3000709@ds.study.iitm.ac.in" || echo "No changes to commit"
          git push
